# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aifn < Formula
  desc "aifn - AI function CLI tool"
  homepage "https://github.com/aifunc-dev/aifunc"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.3.0/aifn_0.3.0_darwin_amd64.tar.gz"
      sha256 "84e8ebbc0d0b678952007e62d698ead788f52a99b8ff7bcd27ed0ae41271feb5"

      define_method(:install) do
        bin.install "aifn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.3.0/aifn_0.3.0_darwin_arm64.tar.gz"
      sha256 "8d140dfa7dd4237cec529ea114b36510f2b2f0bfdb9af61a1f0260742bcc19c4"

      define_method(:install) do
        bin.install "aifn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.3.0/aifn_0.3.0_linux_amd64.tar.gz"
      sha256 "13d42bdfde8a4c9103b80cd92e641910b8e82384536a5585df0ec100bf29c037"
      define_method(:install) do
        bin.install "aifn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.3.0/aifn_0.3.0_linux_arm64.tar.gz"
      sha256 "e6fc51a462f6286be1dd6b414941c4de561c8b8678f02b2d159322cbd87f9fb1"
      define_method(:install) do
        bin.install "aifn"
      end
    end
  end

  test do
    system "#{bin}/aifn", "--version"
  end
end
