# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aifn < Formula
  desc "aifn - AI function CLI tool"
  homepage "https://github.com/aifunc-dev/aifunc"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.1.1/aifn_0.1.1_darwin_amd64.tar.gz"
      sha256 "318e6f7f695522293b5741c1fda626a054e8c5a15de55bf47205e8b4c40a6099"

      define_method(:install) do
        bin.install "aifn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.1.1/aifn_0.1.1_darwin_arm64.tar.gz"
      sha256 "4f5712f1aae9caca5b201506efe0222193e9341ad877b62f2be16d8b33720267"

      define_method(:install) do
        bin.install "aifn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.1.1/aifn_0.1.1_linux_amd64.tar.gz"
      sha256 "ea82c7b137461065a0fc2906b916cbf0342ce220020899792cf0648023732356"
      define_method(:install) do
        bin.install "aifn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aifunc-dev/aifunc/releases/download/v0.1.1/aifn_0.1.1_linux_arm64.tar.gz"
      sha256 "e498fb08c0aa37c71a0e664807bd75ffc3ae305902a14c7662dde079338af04d"
      define_method(:install) do
        bin.install "aifn"
      end
    end
  end

  test do
    system "#{bin}/aifn", "--version"
  end
end
